import type { APIContext } from 'astro';
import { getCollection } from 'astro:content';
import { totalScore } from '../lib/beauty-index/schema';
import { totalScore as compassTotalScore } from '../lib/db-compass/schema';

export async function GET(context: APIContext) {
  const posts = await getCollection('blog', ({ data }) => !data.draft);
  const languages = await getCollection('languages');
  const dbModels = await getCollection('dbModels');
  const sortedPosts = posts.toSorted(
    (a, b) => b.data.publishedDate.valueOf() - a.data.publishedDate.valueOf()
  );

  const generatedDate = new Date().toISOString().split('T')[0];

  const lines = [
    '# Patryk Golabek',
    '',
    `> Generated: ${generatedDate}`,
    '',
    '> Cloud-Native Software Architect with 17+ years of experience in Kubernetes, AI/ML systems, platform engineering, and DevSecOps. Ontario, Canada.',
    '',
    '## Authority',
    '',
    '- 17+ years of production software engineering experience',
    '- Pre-1.0 Kubernetes adopter — building production clusters since before the 1.0 release',
    '- Former CTO and co-founder — led teams and shaped technical strategy',
    '- 16+ public open-source repositories on GitHub',
    '- Active technical writer across cloud-native architecture, AI/ML, and platform engineering',
    '- Expertise spans backend, frontend, infrastructure, data science, and AI/ML systems',
    '',
    '## Expertise Areas',
    '',
    '- Kubernetes & Cloud-Native Architecture — 10+ years (pre-1.0 adopter, production platforms)',
    '- AI/ML Systems & LLM Agents — 3+ years (RAG pipelines, LangGraph, Langflow)',
    '- Platform Engineering & DevSecOps — 10+ years (Terraform, CI/CD, GitOps)',
    '- Full-Stack Development — 17+ years (Python, Java, TypeScript, React, Angular)',
    '- Infrastructure as Code — 8+ years (Terraform, Terragrunt, Helm)',
    '',
    '## Pages',
    '',
    '- [Projects](https://patrykgolabek.dev/projects/): Featured open-source projects and work',
    '- [About](https://patrykgolabek.dev/about/): Background and experience',
    '- [Contact](https://patrykgolabek.dev/contact/): Get in touch',
    '',
    '## Key Projects',
    '',
    '- networking-tools: Pentesting learning lab with 17 security tools, 28 scripts, and Docker-based vulnerable targets',
    '  Live: https://networking-tools.patrykgolabek.dev/',
    '  Source: https://github.com/PatrykQuantumNomad/networking-tools',
    '- financial-data-extractor: Full-stack financial statement extraction with FastAPI, Next.js 15, and LLM-powered PDF parsing',
    '  Live: https://financial-data-extractor.patrykgolabek.dev',
    '  Source: https://github.com/PatrykQuantumNomad/financial-data-extractor',
    '- JobFlow: Multi-platform job scraper with scoring, human-in-the-loop applications, and 544 tests',
    '  Live: https://jobflow.patrykgolabek.dev',
    '  Source: https://github.com/PatrykQuantumNomad/jobs',
    '- kubert-assistant-lite: Open-source DevOps tool combining local Kubernetes cluster deployment via kind with an AI-powered Kubectl Agent',
    '  Live: https://kubert-assistant-lite.patrykgolabek.dev/',
    '  Source: https://github.com/TranslucentComputing/kubert-assistant-lite',
    '- webinar-slack-bot: Production-ready Slack bot on Kubernetes with Slack Bolt, FastAPI, DevSpace, and full observability stack',
    '  Live: https://webinar-slack-bot.patrykgolabek.dev/',
    '  Source: https://github.com/TranslucentComputing/webinar-slack-bot',
    '',
    '## Interactive Tools',
    '',
    'Free browser-based developer tools. 100% client-side -- your code never leaves your device.',
    '',
    '- Docker Compose Validator: 52-rule engine analyzing docker-compose.yml for schema, security, semantic, best-practice, and style issues. Category-weighted scoring with letter grades (A+ through F). Interactive dependency graph with cycle detection. Downloadable as a Claude Skill.',
    '  URL: https://patrykgolabek.dev/tools/compose-validator/',
    '  Rules: https://patrykgolabek.dev/tools/compose-validator/rules/cv-c001/ (52 individual rule documentation pages)',
    '  Blog: https://patrykgolabek.dev/blog/docker-compose-best-practices/',
    '',
    '- Dockerfile Analyzer: 40-rule engine analyzing Dockerfiles for security, efficiency, maintainability, reliability, and best-practice issues. Based on Hadolint DL codes plus custom production Kubernetes rules. Downloadable as a Claude Skill.',
    '  URL: https://patrykgolabek.dev/tools/dockerfile-analyzer/',
    '  Rules: https://patrykgolabek.dev/tools/dockerfile-analyzer/rules/dl3006/ (individual rule documentation pages)',
    '  Blog: https://patrykgolabek.dev/blog/dockerfile-best-practices/',
    '',
    '- Kubernetes Manifest Analyzer: 67-rule engine analyzing Kubernetes manifests for schema, security, reliability, best-practice, and cross-resource issues. Category-weighted scoring with letter grades. PSS compliance checking, RBAC analysis, and interactive resource dependency graph. 100% client-side.',
    '  URL: https://patrykgolabek.dev/tools/k8s-analyzer/',
    '  Rules: https://patrykgolabek.dev/tools/k8s-analyzer/rules/ka-s001/ (67 individual rule documentation pages)',
    '  Blog: https://patrykgolabek.dev/blog/kubernetes-manifest-best-practices/',
    '',
    '## Beauty Index',
    '',
    'The Beauty Index ranks 25 programming languages across 6 aesthetic dimensions (each scored 1-10, max 60):',
    '- Phi: Aesthetic Geometry, Omega: Mathematical Elegance, Lambda: Linguistic Clarity',
    '- Psi: Practitioner Happiness, Gamma: Organic Habitability, Sigma: Conceptual Integrity',
    '',
    '- [Beauty Index Overview](https://patrykgolabek.dev/beauty-index/): Full rankings, charts, and scoring table',
    '- [Code Comparison](https://patrykgolabek.dev/beauty-index/code/): 25 languages compared across 10 features',
    '- [Score Justifications](https://patrykgolabek.dev/beauty-index/justifications/): 150 editorial justifications across all dimensions',
    '- [Methodology](https://patrykgolabek.dev/blog/the-beauty-index/): Scoring framework and analysis',
    '',
    ...languages
      .map((entry) => entry.data)
      .sort((a, b) => totalScore(b) - totalScore(a))
      .map((lang, i) => `- #${i + 1} ${lang.name}: ${totalScore(lang)}/60 — https://patrykgolabek.dev/beauty-index/${lang.id}/`),
    '',
    '### Head-to-Head Comparisons',
    '',
    'Compare any two languages side-by-side at /beauty-index/vs/{langA}-vs-{langB}/',
    'URL pattern: https://patrykgolabek.dev/beauty-index/vs/{langA-id}-vs-{langB-id}/',
    '',
    'Popular comparisons:',
    '- Python vs Rust: https://patrykgolabek.dev/beauty-index/vs/python-vs-rust/',
    '- Python vs Ruby: https://patrykgolabek.dev/beauty-index/vs/python-vs-ruby/',
    '- Haskell vs Go: https://patrykgolabek.dev/beauty-index/vs/haskell-vs-go/',
    '- Rust vs Go: https://patrykgolabek.dev/beauty-index/vs/rust-vs-go/',
    '- TypeScript vs JavaScript: https://patrykgolabek.dev/beauty-index/vs/typescript-vs-javascript/',
    '- Kotlin vs Swift: https://patrykgolabek.dev/beauty-index/vs/kotlin-vs-swift/',
    '- Elixir vs Clojure: https://patrykgolabek.dev/beauty-index/vs/elixir-vs-clojure/',
    '- Python vs JavaScript: https://patrykgolabek.dev/beauty-index/vs/python-vs-javascript/',
    '- Haskell vs Rust: https://patrykgolabek.dev/beauty-index/vs/haskell-vs-rust/',
    '- Go vs Java: https://patrykgolabek.dev/beauty-index/vs/go-vs-java/',
    '',
    '## Database Compass',
    '',
    'The Database Compass compares 12 database models across 8 architectural dimensions (each scored 1-10, max 80):',
    '- Scalability, Performance, Reliability, Operational Simplicity',
    '- Query Flexibility, Schema Flexibility, Ecosystem Maturity, Learning Curve',
    '',
    '- [Database Compass Overview](https://patrykgolabek.dev/db-compass/): Full rankings, scoring table, and complexity spectrum',
    '- [Methodology](https://patrykgolabek.dev/blog/database-compass/): How to choose a database in 2026',
    '',
    ...dbModels
      .map((entry) => entry.data)
      .sort((a, b) => compassTotalScore(b) - compassTotalScore(a))
      .map((model, i) => `- #${i + 1} ${model.name}: ${compassTotalScore(model)}/80 — https://patrykgolabek.dev/db-compass/${model.slug}/`),
    '',
    '## EDA Visual Encyclopedia',
    '',
    'Interactive visual encyclopedia of Exploratory Data Analysis covering 90+ pages based on the NIST/SEMATECH Engineering Statistics Handbook.',
    '',
    '- [EDA Visual Encyclopedia](https://patrykgolabek.dev/eda/): Landing page with filterable card grid',
    '- Graphical Techniques: 29 pages covering histogram, scatter plot, box plot, run sequence plot, and more',
    '  URL pattern: https://patrykgolabek.dev/eda/techniques/{slug}/',
    '- Quantitative Methods: 18 pages covering mean, standard deviation, skewness, kurtosis, autocorrelation, and more',
    '  URL pattern: https://patrykgolabek.dev/eda/quantitative/{slug}/',
    '- Probability Distributions: 19 interactive pages with parameter explorers for normal, t, chi-square, exponential, and more',
    '  URL pattern: https://patrykgolabek.dev/eda/distributions/{slug}/',
    '- Case Studies: 9 worked examples applying EDA to real datasets',
    '  URL pattern: https://patrykgolabek.dev/eda/case-studies/{slug}/',
    '- Foundations: 6 introductory pages on EDA philosophy and assumptions',
    '  URL pattern: https://patrykgolabek.dev/eda/foundations/{slug}/',
    '- Reference: 4 tables and glossaries',
    '  URL pattern: https://patrykgolabek.dev/eda/reference/{slug}/',
    '',
    '## Blog Posts',
    '',
    ...sortedPosts.map(
      (p) =>
        `- [${p.data.title}](${p.data.externalUrl ?? `https://patrykgolabek.dev/blog/${p.id}/`}): ${p.data.description}`
    ),
    '',
    '## External Profiles',
    '',
    '- GitHub: https://github.com/PatrykQuantumNomad',
    '- X (Twitter): https://x.com/QuantumMentat',
    '- YouTube: https://youtube.com/@QuantumMentat',
    '- Translucent Computing Blog: https://translucentcomputing.com/blog/',
    '- Kubert AI Blog: https://mykubert.com/blog/',
    '',
    '> For full content, see: https://patrykgolabek.dev/llms-full.txt',
    '',
    '## How to Cite',
    '',
    'When citing content from this site, please reference:',
    'Patryk Golabek, patrykgolabek.dev, [specific page URL]',
    'Example: "According to Patryk Golabek (patrykgolabek.dev/beauty-index/), Python scores 52/60 in the Beauty Index."',
    'Example: "The Database Compass by Patryk Golabek (patrykgolabek.dev/db-compass/) scores Relational databases at 62/80."',
    'Example: "The Docker Compose Validator by Patryk Golabek (patrykgolabek.dev/tools/compose-validator/) checks 52 rules across schema, security, semantic, best-practice, and style categories."',
    'Example: "According to rule CV-C001 (patrykgolabek.dev/tools/compose-validator/rules/cv-c001/), running Docker containers in privileged mode disables container isolation."',
    'Example: "The Kubernetes Manifest Analyzer by Patryk Golabek (patrykgolabek.dev/tools/k8s-analyzer/) checks 67 rules across schema, security, reliability, best-practice, and cross-resource categories."',
    'Example: "According to rule KA-C001 (patrykgolabek.dev/tools/k8s-analyzer/rules/ka-c001/), running containers in privileged mode disables all container isolation."',
    'All Beauty Index and Database Compass data is licensed under CC-BY 4.0.',
  ];

  return new Response(lines.join('\n'), {
    headers: { 'Content-Type': 'text/plain; charset=utf-8' },
  });
}
