import type { ComposeLintRule } from '../types';
import { semanticRules } from './semantic';
import { securityRules } from './security';
import { bestPracticeRules } from './best-practice';
import { styleRules } from './style';

// NOTE: Schema rules are NOT included here -- they use SchemaRuleMetadata (no check method).
// Schema violations are generated by categorizeSchemaErrors() in schema-validator.ts.
// Total rules in the system: 52 (44 custom with check() + 8 schema metadata).

/** All custom lint rules with check() methods. 44 total (15 semantic + 14 security + 12 best-practice + 3 style). */
export const allComposeRules: ComposeLintRule[] = [
  ...semanticRules,
  ...securityRules,
  ...bestPracticeRules,
  ...styleRules,
];

/** Look up a rule by ID. Returns undefined if not found. */
export function getComposeRuleById(id: string): ComposeLintRule | undefined {
  return allComposeRules.find((r) => r.id === id);
}
