import type { ComposeLintRule, ComposeSeverity, ComposeCategory, ComposeRuleFix } from '../types';
import { semanticRules } from './semantic';
import { securityRules } from './security';
import { bestPracticeRules } from './best-practice';
import { styleRules } from './style';
import { schemaRules } from './schema';

// NOTE: Schema rules use SchemaRuleMetadata (no check method).
// Schema violations are generated by categorizeSchemaErrors() in schema-validator.ts.
// Total rules in the system: 52 (44 custom with check() + 8 schema metadata).

/** Common documentation shape shared by ComposeLintRule and SchemaRuleMetadata. */
export interface DocumentedRule {
  id: string;
  title: string;
  severity: ComposeSeverity;
  category: ComposeCategory;
  explanation: string;
  fix: ComposeRuleFix;
}

/** All custom lint rules with check() methods. 44 total (15 semantic + 14 security + 12 best-practice + 3 style). */
export const allComposeRules: ComposeLintRule[] = [
  ...semanticRules,
  ...securityRules,
  ...bestPracticeRules,
  ...styleRules,
];

/** All 52 documented rules (44 custom + 8 schema) for static page generation. */
export const allDocumentedRules: DocumentedRule[] = [
  ...(allComposeRules as DocumentedRule[]),
  ...(schemaRules as DocumentedRule[]),
];

/** Look up a rule by ID. Returns undefined if not found. */
export function getComposeRuleById(id: string): ComposeLintRule | undefined {
  return allComposeRules.find((r) => r.id === id);
}
