import type { K8sLintRule, K8sSeverity, K8sCategory, K8sRuleFix } from '../types';
import { securityRules } from './security';
import { reliabilityRules } from './reliability';
import { bestPracticeRules } from './best-practice';

// NOTE: Schema rules use SchemaRuleMetadata (no check method).
// Schema violations are generated by the schema-validator.

/** Common documentation shape shared by K8sLintRule and SchemaRuleMetadata. */
export interface DocumentedK8sRule {
  id: string;
  title: string;
  severity: K8sSeverity;
  category: K8sCategory;
  explanation: string;
  fix: K8sRuleFix;
}

/** All custom lint rules with check() methods. */
export const allK8sRules: K8sLintRule[] = [
  ...securityRules,
  ...reliabilityRules,
  ...bestPracticeRules,
];

/** All documented rules for static page generation. */
export const allDocumentedK8sRules: DocumentedK8sRule[] = [
  ...(allK8sRules as DocumentedK8sRule[]),
];

/** Look up a rule by ID. Returns undefined if not found. */
export function getK8sRuleById(id: string): K8sLintRule | undefined {
  return allK8sRules.find((r) => r.id === id);
}
